[build]
  command = "node env.js && ng build --configuration=production"
  publish = "dist/profile-dashboard/browser" # Change to your Angular output path if different


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
